workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master"

stages:
  - test

.poetry_common: &poetry_common
  before_script:
    - poetry install
  image:
    name: nexus-docker.ops.gitential.com/python-poetry:v1-py3.8.6-build
    entrypoint: [""]

poetry_invoke_lint:
  extends: .poetry_common
  stage: test
  script:
    - poetry run invoke lint

unit_tests:
  extends: .ge_poetry_common
  stage: test
  script:
    - poetry run invoke unit-test
