FROM docker-internal.gitential.io/python-poetry:v5-py3.10.2-build as build
USER root
RUN mkdir -p /builds/gitential-com/gitential2
RUN chown app:app /builds -R

USER app
WORKDIR /builds/gitential-com/gitential2

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root
