version: "3.7"

services:
  # development:
  #   build: .
  #   ports:
  #     - "7998:7998"
  #   volumes:
  #     - .:/project/app
  #   environment:
  #     ENVFILE_PATH: .secrets.env
  #   entrypoint: [ "echo", "Service foo disabled" ]
  #   restart: "no"

  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: gitential
      POSTGRES_USER: gitential
      POSTGRES_PASSWORD: secret123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gitential.com
      PGADMIN_DEFAULT_PASSWORD: secret123
      PGADMIN_LISTEN_PORT: 8079
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:db"
    ports:
      - "8079:8079"
  redis:
    image: redis:6.0.10
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  nginx:
    build: nginx/
    network_mode: host

volumes:
  db-data: null
  pgadmin-data: null
  redis-data: null
