log_level: info
executor: process_pool
show_progress: true
backend: sql
backend_connection: postgresql://gitential:secret123@localhost:5432/gitential
repository_sources:
  gitlab:
    source_type: gitlab
    base_url: https://gitlab.ops.gitential.com
    client_id: "d043df035355fe747d2a62d35b0f6089cff4c8c45fb8ca0066459792e388230d"
    client_secret: "9bcb53d633178a83b3e46849bcec95d3d2c15d817bc48c1a1e35a84e8a4964c7"
    use_as_login: true
    login_text: "Login with gitlab.ops"
