maintenance:
  enabled: false
log_level: info
extraction:
  show_progress: false
  executor: process_pool
web:
  base_url: https://localhost:8443
  frontend_url: https://localhost:8443
  enforce_base_url: true
  legacy_login: false
  access_log: true
  session_https_only: true
  session_same_site: "Lax"
  session_max_age: 86400
  # base_url: https://590027f52278.ngrok.io

secret: abcdABCDabcdABCDabcdABCDabcdABCD
backend: sql
email:
  sender: laszlo.andrasi@gitential.com
  smtp_host: email-smtp.us-east-1.amazonaws.com
  smtp_port: 587
  smtp_username: AKIA4G3GM7INBOETB3XG
  smtp_password: BKWXqc4jofWzDrbS0ZgYuhrAngjlAq/5NvWjJJCLdZkh
notifications:
  system_notification_recipient: laszlo.andrasi@gitential.com
  request_free_trial: false
recaptcha:
  site_key: 6LftqHEaAAAAANgRbGA6Ew6nToApMx3TysEMYa-y
  secret_key: 6LftqHEaAAAAABt-WU7zTL9WHbv49GzWGuAjJiH8
stripe:
  api_key: "sk_test_rTy8rIts8T5ePsU8Mu9G0tyG00zZWBqBSJ"
  publishable_key: "pk_test_8NvkMx8TUGYMVgxgHda7Ly4400OqJK6Caz"
  private_key: "sk_test_rTy8rIts8T5ePsU8Mu9G0tyG00zZWBqBSJ"
  price_id_monthly: "price_1JDnUJFFL0UUh0zzefPuFoKf"
  price_id_yearly: "price_1JDnUJFFL0UUh0zzBizI1UvN"
  webhook_secret: "whsec_J3wwXzXQOklhlC5qS9iCFynVkiHzXZ9g"
# frontend:
#   inject_html:
#     - tag: script
#       attributes:
#         async: true
#         src: "https://www.googletagmanager.com/gtag/js?id=UA-168824170-2"
#     - tag: script
#       content: |
#         /* Hotjar Tracking Code for https://app.gitential.com/ */
#         if (document.location.hostname === 'app.gitential.com') {
#             (function (h, o, t, j, a, r) {
#                 h.hj = h.hj || function () {
#                     (h.hj.q = h.hj.q || []).push(arguments)
#                 };
#                 h._hjSettings = { hjid: 1974992, hjsv: 6 };
#                 a = o.getElementsByTagName('head')[0];
#                 r = o.createElement('script');
#                 r.async = 1;
#                 r.src = t + h._hjSettings.hjid + j + h._hjSettings.hjsv;
#                 a.appendChild(r);
#             })(window, document, 'https://static.hotjar.com/c/hotjar-', '.js?sv=');
#         }

#     - tag: script
#       content: |
#         /* google analytics tracking code */
#         if (document.location.hostname === 'app.gitential.com') {
#             window.dataLayer = window.dataLayer || [];
#             function gtag() {
#                 dataLayer.push(arguments);
#             }
#             gtag('js', new Date());
#             gtag('config', 'UA-168824170-2');
#         }

#     - tag: script
#       parent: body
#       position: afterbegin
#       content: |
#         (function() {
#           var s = document.getElementsByTagName("script")[0];
#           var b = document.createElement("script");
#           b.type = "text/javascript";
#           b.async = true;
#           b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
#           s.parentNode.insertBefore(b, s);
#         })();

#     - tag: script
#       parent: body
#       position: afterbegin
#       content: |
#         _linkedin_partner_id = "2061993";
#         window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
#         window._linkedin_data_partner_ids.push(_linkedin_partner_id);

connections:
  database_url: postgresql://gitential:secret123@localhost:5432/gitential
  redis_url: redis://localhost:6379/0
  s3:
    aws_access_key_id: access_key_id
    aws_secret_access_key: secret_access_key
    bucket_name: gitential-internal-data
integrations:
  gitlab-internal:
    type: gitlab
    display_name: GitLab self-hosted
    base_url: https://gitlab.ops.gitential.com
    oauth:
      client_id: "d043df035355fe747d2a62d35b0f6089cff4c8c45fb8ca0066459792e388230d"
      client_secret: "9bcb53d633178a83b3e46849bcec95d3d2c15d817bc48c1a1e35a84e8a4964c7"
    login: true
  gitlab-com:
    type: gitlab
    display_name: GitLab.COM
    base_url: https://gitlab.com
    oauth:
      client_id: "9ec1b46773e985147690b173c1bafd3d423ef2c7d1d5f19809483e92f000c770"
      client_secret: "e5825ffa36b8973b02c8a2c5650ab86663619f62f23d4c61a7e9f9eec5b7c3e9"
    login: true
    login_order: -100
  github:
    type: github
    display_name: GitHub
    oauth:
      client_id: "7ef5d2a52e581f7bfaf0"
      client_secret: "2cb2261386aac7d1ab8a587fdccffd24cf59aada"
    login: true
    login_text: "Login with GitHub"

  bitbucket:
    type: bitbucket
    oauth:
      client_id: "SHgqHHRXqeg3xeGguJ"
      client_secret: "Dw5HSd6EGD7MY7q3YeXpWPKGTh4JDJgA"
    login: true
    login_text: "Login with BitBucket"
    display_name: "BitBucket"

  vsts:
    type: vsts
    oauth:
      client_id: 6621D0FB-1961-4699-B0CD-A11919C42599
      client_secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJjaWQiOiI2NjIxZDBmYi0xOTYxLTQ2OTktYjBjZC1hMTE5MTljNDI1OTkiLCJjc2kiOiI4YjZjOTY2YS1iZDI1LTQ4ODEtYWQ4Mi0xNmYxNzlhZDc2N2UiLCJuYW1laWQiOiJiNjE5MmMxYy0zODk4LTY1YzItODc2NC1kYTg5NGRhZDQ5ODIiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsIm5iZiI6MTYyMDA1MjI0MSwiZXhwIjoxNzc3ODE4NjQxfQ.TN1pQBHPxIITX1eKtwpsd-nQby1u-vncHAWyOnCpB_Ny98SNK4I2GILO2wofIY736ik9mJ0lZWLSc-Be4za2_nUHm3NjiWIMiRTXJmvJlC9yBu_GduKlyPTmPvTdjzzaopOllr9vuieR-6chGmsrDBqvyEzzdZNxVUYZIV6pizkUSHbjFomgaW5mjyrQeSfrdEUTK0-YWIweTxx4tUrWosEHkCVtRHbsVG7Omqid0AKw-8Jr6qxa860Kmx6E85Q7ZM1B9p7USm3Bav3Vrab2wfFw_aCWNEGsdBUqFvnzgkBlkR0E__51BsJOPTRhZzkLH5in6fAumLueXMU6Oc1_vA
    login: true
    display_name: "Azure DevOps"
    options:
      redirect_url: https://localhost:8443/v2/auth/vsts

  linkedin:
    type: linkedin
    login: true
    login_top_text: "You don't have a git account?"
    login_order: 100
    oauth:
      client_id: 78niu9tfn4fufa
      client_secret: 1LH59EYaQQnxGAHn
