from fastapi import APIRouter, Query

router = APIRouter(tags=["repositories"])


@router.get("/workspaces/{workspace_id}/available-repos")
async def available_repos(workspace_id: int):
    # már hozzáadott ssh repokat
    # gitlab, github, stb. api kéréséből származó repo-kat
    return available_repos_data


@router.get("/workspaces/{workspace_id}/repos")
async def workspace_repos(workspace_id: int):
    return [
        {
            "id": 1072,
            "name": "php-src",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/php\/php-src.git",
            "github_id": 1903522,
            "source": "php",
        },
        {
            "id": 16048,
            "name": "confidant",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/lyft\/confidant.git",
            "github_id": 42324225,
            "source": "lyft",
        },
        {
            "id": 16049,
            "name": "cartography",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/lyft\/cartography.git",
            "github_id": 172811550,
            "source": "lyft",
        },
        {
            "id": 16050,
            "name": "mapper",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/lyft\/mapper.git",
            "github_id": 44777644,
            "source": "lyft",
        },
        {
            "id": 16051,
            "name": "flyte",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/lyft\/flyte.git",
            "github_id": 216628419,
            "source": "lyft",
        },
        {
            "id": 16052,
            "name": "amundsen",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/lyft\/amundsen.git",
            "github_id": 186647681,
            "source": "lyft",
        },
        {
            "id": 16071,
            "name": "hyperscan",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/intel\/hyperscan.git",
            "github_id": 42895929,
            "source": "intel",
        },
        {
            "id": 16077,
            "name": "terraform-provider-restapi",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/Mastercard\/terraform-provider-restapi.git",
            "github_id": 131317436,
            "source": "Mastercard",
        },
        {
            "id": 16078,
            "name": "oauth1-signer-nodejs",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/Mastercard\/oauth1-signer-nodejs.git",
            "github_id": 132767011,
            "source": "Mastercard",
        },
        {
            "id": 16243,
            "name": "fork",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/shazam\/fork.git",
            "github_id": 25603410,
            "source": "shazam",
        },
        {
            "id": 16244,
            "name": "shazamcrest",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/shazam\/shazamcrest.git",
            "github_id": 8851918,
            "source": "shazam",
        },
        {
            "id": 16245,
            "name": "app-store-reviews-and-translations",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/shazam\/app-store-reviews-and-translations.git",
            "github_id": 87566936,
            "source": "shazam",
        },
        {
            "id": 16246,
            "name": "jenkins-nodes-auto-scaler",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/shazam\/jenkins-nodes-auto-scaler.git",
            "github_id": 91446275,
            "source": "shazam",
        },
        {
            "id": 16247,
            "name": "scala-datapipeline-dsl",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/shazam\/scala-datapipeline-dsl.git",
            "github_id": 130351052,
            "source": "shazam",
        },
        {
            "id": 16248,
            "name": "rapidminer-studio",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/rapidminer\/rapidminer-studio.git",
            "github_id": 41420773,
            "source": "rapidminer",
        },
        {
            "id": 16249,
            "name": "rapidminer-5",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/rapidminer\/rapidminer-5.git",
            "github_id": 11948968,
            "source": "rapidminer",
        },
        {
            "id": 16250,
            "name": "eventbrite-client-py",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/eventbrite\/eventbrite-client-py.git",
            "github_id": 2194433,
            "source": "eventbrite",
        },
        {
            "id": 16251,
            "name": "javascript",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/eventbrite\/javascript.git",
            "github_id": 59158617,
            "source": "eventbrite",
        },
        {
            "id": 16252,
            "name": "entando-cms",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/entando\/entando-cms.git",
            "github_id": 195347425,
            "source": "entando",
        },
        {
            "id": 16253,
            "name": "entando-ux-packages",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/entando\/entando-ux-packages.git",
            "github_id": 23320007,
            "source": "entando",
        },
        {
            "id": 16258,
            "name": "insomnia-plugin-mastercard-auth",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/Mastercard\/insomnia-plugin-mastercard-auth.git",
            "github_id": 127004734,
            "source": "Mastercard",
        },
        {
            "id": 16259,
            "name": "fido2-rp-spring",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/Mastercard\/fido2-rp-spring.git",
            "github_id": 135557268,
            "source": "Mastercard",
        },
        {
            "id": 16260,
            "name": "facebook-android-sdk",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/facebook\/facebook-android-sdk.git",
            "github_id": 659341,
            "source": "facebook",
        },
        {
            "id": 16261,
            "name": "facebook-ios-sdk",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/facebook\/facebook-ios-sdk.git",
            "github_id": 738491,
            "source": "facebook",
        },
        {
            "id": 16262,
            "name": "flux",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/facebook\/flux.git",
            "github_id": 22046023,
            "source": "facebook",
        },
        {
            "id": 16263,
            "name": "PayPal-PHP-SDK",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/paypal\/PayPal-PHP-SDK.git",
            "github_id": 8595323,
            "source": "paypal",
        },
        {
            "id": 16264,
            "name": "PayPal-Java-SDK",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/paypal\/PayPal-Java-SDK.git",
            "github_id": 8595333,
            "source": "paypal",
        },
        {
            "id": 16265,
            "name": "ph-css",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/phax\/ph-css.git",
            "github_id": 23304527,
            "source": "phax",
        },
        {
            "id": 16266,
            "name": "phase4",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/phax\/phase4.git",
            "github_id": 62138020,
            "source": "phax",
        },
        {
            "id": 16267,
            "name": "ph-ubl",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/phax\/ph-ubl.git",
            "github_id": 23310687,
            "source": "phax",
        },
        {
            "id": 16268,
            "name": "as2-peppol-server",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/phax\/as2-peppol-server.git",
            "github_id": 26581813,
            "source": "phax",
        },
        {
            "id": 16269,
            "name": "phoss-smp",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/phax\/phoss-smp.git",
            "github_id": 32790911,
            "source": "phax",
        },
        {
            "id": 16270,
            "name": "phaser",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/photonstorm\/phaser.git",
            "github_id": 9393759,
            "source": "photonstorm",
        },
        {
            "id": 16271,
            "name": "InputSystem",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/Unity-Technologies\/InputSystem.git",
            "github_id": 105615454,
            "source": "Unity-Technologies",
        },
        {
            "id": 16272,
            "name": "arfoundation-samples",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/Unity-Technologies\/arfoundation-samples.git",
            "github_id": 137433882,
            "source": "Unity-Technologies",
        },
        {
            "id": 16273,
            "name": "xing-android-sdk",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/xing\/xing-android-sdk.git",
            "github_id": 39831872,
            "source": "xing",
        },
        {
            "id": 16274,
            "name": "beetle",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/xing\/beetle.git",
            "github_id": 472219,
            "source": "xing",
        },
        {
            "id": 16275,
            "name": "xing_api",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/xing\/xing_api.git",
            "github_id": 14297694,
            "source": "xing",
        },
        {
            "id": 16276,
            "name": "xing_nlp",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/shixing\/xing_nlp.git",
            "github_id": 90913752,
            "source": "shixing",
        },
        {
            "id": 16277,
            "name": "xing-api-samples",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/xing\/xing-api-samples.git",
            "github_id": 14494694,
            "source": "xing",
        },
        {
            "id": 16278,
            "name": "XNGMarkdownParser",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/xing\/XNGMarkdownParser.git",
            "github_id": 23104196,
            "source": "xing",
        },
        {
            "id": 16279,
            "name": "swift-style-guide",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/linkedin\/swift-style-guide.git",
            "github_id": 61673934,
            "source": "linkedin",
        },
        {
            "id": 16280,
            "name": "databus",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/linkedin\/databus.git",
            "github_id": 7209229,
            "source": "linkedin",
        },
        {
            "id": 16281,
            "name": "player-api",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/vimeo\/player-api.git",
            "github_id": 1527472,
            "source": "vimeo",
        },
        {
            "id": 16282,
            "name": "vimeo.py",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/vimeo\/vimeo.py.git",
            "github_id": 15173209,
            "source": "vimeo",
        },
        {
            "id": 16283,
            "name": "vimeo-php-lib",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/vimeo\/vimeo-php-lib.git",
            "github_id": 747652,
            "source": "vimeo",
        },
        {
            "id": 16284,
            "name": "vimeo-oembed-examples",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/vimeo\/vimeo-oembed-examples.git",
            "github_id": 769357,
            "source": "vimeo",
        },
        {
            "id": 16285,
            "name": "bootstrap",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/twbs\/bootstrap.git",
            "github_id": 2126244,
            "source": "twbs",
        },
        {
            "id": 16286,
            "name": "icons",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/twbs\/icons.git",
            "github_id": 198878888,
            "source": "twbs",
        },
        {
            "id": 16287,
            "name": "rfs",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/twbs\/rfs.git",
            "github_id": 93316445,
            "source": "twbs",
        },
        {
            "id": 16288,
            "name": "bootlint",
            "secret_id": 2410,
            "clone_url": "https:\/\/github.com\/twbs\/bootlint.git",
            "github_id": 21428312,
            "source": "twbs",
        },
    ]


@router.get("/workspaces/{workspace_id}/projects/{project_id}/repos")
async def project_repos(workspace_id: int, project_id: int):
    if project_id == 2496:
        return [
            {
                "secret_id": 2410,
                "clone_url": "https:\/\/github.com\/entando\/entando-cms.git",
                "github_id": 195347425,
                "id": 16252,
                "private": True,
                "name": "entando-cms",
                "source": "entando",
                "secret_source": "github",
            },
            {
                "secret_id": 2410,
                "clone_url": "https:\/\/github.com\/entando\/entando-ux-packages.git",
                "github_id": 23320007,
                "private": True,
                "id": 16253,
                "name": "entando-ux-packages",
                "source": "entando",
                "secret_source": "github",
            },
        ]
    else:
        return []


available_repos_data = [
    {
        "source": "entando",
        "type": "github",
        "items": [
            {
                "secret_id": 2410,
                "clone_url": "https:\/\/github.com\/entando\/entando-cms.git",
                "github_id": 195347425,
                "id": 16252,
                "name": "entando-cms",
                "private": True,
                "source": "entando",
                "secret_source": "github",
            },
            {
                "secret_id": 2410,
                "clone_url": "https:\/\/github.com\/entando\/entando-ux-packages.git",
                "github_id": 23320007,
                "id": 16253,
                "private": True,
                "name": "entando-ux-packages",
                "source": "entando",
                "secret_source": "github",
            },
        ],
    },
    {
        "source": "benbal87",
        "items": [
            {
                "clone_url": "https://github.com/benbal87/java-practices.git",
                "name": "java-practices",
                "source": "benbal87",
                "secret_source": "github",
                "private": False,
                "github_id": 262872487,
            },
            {
                "clone_url": "https://github.com/benbal87/javascript-practices.git",
                "name": "javascript-practices",
                "source": "benbal87",
                "secret_source": "github",
                "private": False,
                "github_id": 263102903,
            },
            {
                "clone_url": "https://github.com/benbal87/photo-album-organizer.git",
                "name": "photo-album-organizer",
                "source": "benbal87",
                "secret_source": "github",
                "private": False,
                "github_id": 262773956,
            },
            {
                "clone_url": "https://github.com/benbal87/spring-boot-security-jwt-react-postgresql.git",
                "name": "spring-boot-security-jwt-react-postgresql",
                "source": "benbal87",
                "secret_source": "github",
                "private": False,
                "github_id": 259212726,
            },
            {
                "clone_url": "https://github.com/benbal87/strip-accents.git",
                "name": "strip-accents",
                "source": "benbal87",
                "secret_source": "github",
                "private": False,
                "github_id": 262774407,
            },
            {
                "clone_url": "https://github.com/benbal87/unicode-string-converter.git",
                "name": "unicode-string-converter",
                "source": "benbal87",
                "secret_source": "github",
                "private": False,
                "github_id": 262774223,
            },
        ],
        "type": "github",
    },
    {
        "source": "Gitential-com",
        "items": [
            {
                "clone_url": "https://github.com/Gitential-com/apis.git",
                "name": "apis",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 70683870,
            },
            {
                "clone_url": "https://github.com/Gitential-com/aws-environment.git",
                "name": "aws-environment",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 210826896,
            },
            {
                "clone_url": "https://github.com/Gitential-com/baseimage.git",
                "name": "baseimage",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 285502935,
            },
            {
                "clone_url": "https://github.com/Gitential-com/catwalk.git",
                "name": "catwalk",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 54195279,
            },
            {
                "clone_url": "https://github.com/Gitential-com/cyclones.git",
                "name": "cyclones",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 81270091,
            },
            {
                "clone_url": "https://github.com/Gitential-com/datasets.git",
                "name": "datasets",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": False,
                "github_id": 117517570,
            },
            {
                "clone_url": "https://github.com/Gitential-com/feedback.git",
                "name": "feedback",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": False,
                "github_id": 105461208,
            },
            {
                "clone_url": "https://github.com/Gitential-com/filetype_classification.git",
                "name": "filetype_classification",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 211390482,
            },
            {
                "clone_url": "https://github.com/Gitential-com/gc-data.git",
                "name": "gc-data",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 43805816,
            },
            {
                "clone_url": "https://github.com/Gitential-com/ge-public-api.git",
                "name": "ge-public-api",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 55521586,
            },
            {
                "clone_url": "https://github.com/Gitential-com/ge-siteplan.git",
                "name": "ge-siteplan",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 66007077,
            },
            {
                "clone_url": "https://github.com/Gitential-com/gitcruit.git",
                "name": "gitcruit",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 43682034,
            },
            {
                "clone_url": "https://github.com/Gitential-com/gitential.git",
                "name": "gitential",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 54567827,
            },
            {
                "clone_url": "https://github.com/Gitential-com/gitential.github.io.git",
                "name": "gitential.github.io",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 109396913,
            },
            {
                "clone_url": "https://github.com/Gitential-com/gitex.git",
                "name": "gitex",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 285562131,
            },
            {
                "clone_url": "https://github.com/Gitential-com/gitrics.git",
                "name": "gitrics",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 79133097,
            },
            {
                "clone_url": "https://github.com/Gitential-com/gitrix.git",
                "name": "gitrix",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 82795031,
            },
            {
                "clone_url": "https://github.com/Gitential-com/hooker.git",
                "name": "hooker",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 76459063,
            },
            {
                "clone_url": "https://github.com/Gitential-com/licence.git",
                "name": "licence",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 207007533,
            },
            {
                "clone_url": "https://github.com/Gitential-com/license-manager.git",
                "name": "license-manager",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 211618872,
            },
            {
                "clone_url": "https://github.com/Gitential-com/maerks.git",
                "name": "maerks",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 97022862,
            },
            {
                "clone_url": "https://github.com/Gitential-com/notebooks.git",
                "name": "notebooks",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 214185220,
            },
            {
                "clone_url": "https://github.com/Gitential-com/onpremise.git",
                "name": "onpremise",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 103369504,
            },
            {
                "clone_url": "https://github.com/Gitential-com/pandahouse.git",
                "name": "pandahouse",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 213347247,
            },
            {
                "clone_url": "https://github.com/Gitential-com/papi.git",
                "name": "papi",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 85198454,
            },
            {
                "clone_url": "https://github.com/Gitential-com/regit.git",
                "name": "regit",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 267222573,
            },
            {
                "clone_url": "https://github.com/Gitential-com/rush.git",
                "name": "rush",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 116967809,
            },
            {
                "clone_url": "https://github.com/Gitential-com/sewong.git",
                "name": "sewong",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 97029561,
            },
            {
                "clone_url": "https://github.com/Gitential-com/slides.git",
                "name": "slides",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 86452986,
            },
            {
                "clone_url": "https://github.com/Gitential-com/testrepo.git",
                "name": "testrepo",
                "source": "Gitential-com",
                "secret_source": "github",
                "private": True,
                "github_id": 291059140,
            },
        ],
        "type": "github",
    },
    {
        "source": "gitential-com",
        "items": [
            {
                "clone_url": "https://gitlab.com/gitential-com/papi.git",
                "name": "papi",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23446092,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/infrastructure.git",
                "name": "infrastructure",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23445799,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/gitrix.git",
                "name": "gitrix",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23445794,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/cyclones.git",
                "name": "cyclones",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23445790,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/catwalk.git",
                "name": "catwalk",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23445783,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/aws-environment.git",
                "name": "aws-environment",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23445773,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/python-poetry-base.git",
                "name": "python-poetry-base",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23097815,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/gitential2.git",
                "name": "gitential2",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 23095294,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/test-repository.git",
                "name": "test-repository",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 22482844,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/public-parrot.git",
                "name": "public-parrot",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 21049498,
            },
            {
                "clone_url": "https://gitlab.com/gitential-com/gitex.git",
                "name": "gitex",
                "source": "gitential-com",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 21027392,
            },
        ],
        "type": "gitlab",
        "logo": {"colored": "/251cb6a63e5f5c429b971c5597fb4dbb.svg", "grey": "/3ca5e6a3ef5ed3215b04431fba1fcb20.svg"},
        "id": "15d76b63-3714-40ea-aa1b-875062fc09fe",
    },
    {
        "source": "benbal87",
        "items": [
            {
                "clone_url": "https://gitlab.com/benbal87/teka-cleaner.git",
                "name": "teka-cleaner",
                "source": "benbal87",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 12346244,
            },
            {
                "clone_url": "https://gitlab.com/benbal87/category-datasheet-modification-sitebuild.git",
                "name": "category-datasheet-modification-sitebuild",
                "source": "benbal87",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 10537972,
            },
            {
                "clone_url": "https://gitlab.com/benbal87/bnd-file-rewrite.git",
                "name": "bnd-file-rewrite",
                "source": "benbal87",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 10424785,
            },
            {
                "clone_url": "https://gitlab.com/benbal87/newsboard-admin.git",
                "name": "newsboard-admin",
                "source": "benbal87",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 7822859,
            },
            {
                "clone_url": "https://gitlab.com/benbal87/newsboard.git",
                "name": "newsboard",
                "source": "benbal87",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 7822839,
            },
            {
                "clone_url": "https://gitlab.com/benbal87/uDecimalMask.git",
                "name": "uDecimalMask",
                "source": "benbal87",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 4192120,
            },
        ],
        "type": "gitlab",
    },
    {
        "source": "adbank",
        "items": [
            {
                "clone_url": "https://gitlab.com/adbank/admin.git",
                "name": "admin",
                "source": "adbank",
                "secret_source": "gitlab",
                "private": True,
                "gitlab_id": 2101270,
            }
        ],
        "type": "gitlab",
    },
]
